name: CI

on: [push, pull_request]

jobs:

  test-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
          sudo apt-get update
          sudo apt-get -y install uuid-dev libcurl4-openssl-dev
          make KEYDB_CFLAGS='-Werror' KEYDB_CXXFLAGS='-Werror' BUILD_TLS=yes -j2
    - name: gen-cert
      run: ./utils/gen-test-certs.sh
    - name: test-tls
      run: |
        sudo apt-get -y install tcl tcl-tls
        ./runtest --clients 2 --verbose --tls
    - name: cluster-test
      run: |
        ./runtest-cluster --tls
    - name: sentinel test
      run: |
          ./runtest-sentinel
    - name: module tests
      run: |
          ./runtest-moduleapi
        
  build-ubuntu-old:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: make -j2
      run: | 
        sudo apt-get update
        sudo apt-get -y install uuid-dev libcurl4-openssl-dev
        make -j2

  build-macos-latest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make KEYDB_CFLAGS='-Werror' KEYDB_CXXFLAGS='-Werror' -j2

  build-libc-malloc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
          sudo apt-get update
          sudo apt-get -y install uuid-dev libcurl4-openssl-dev
          make KEYDB_CFLAGS='-Werror' KEYDB_CXXFLAGS='-Werror' MALLOC=libc -j2

